INSERT INTO PHONEBOOKENTRIES (ID, NAME, PHONENUMBER) VALUES (99, 'Bob', '12');
INSERT INTO PHONEBOOKENTRIES (ID, NAME, PHONENUMBER) VALUES (100, 'Tim', '34');
INSERT INTO PHONEBOOKENTRIES (ID, NAME, PHONENUMBER) VALUES (101, 'Joe', '56');
INSERT INTO PHONEBOOKENTRIES (ID, NAME, PHONENUMBER) VALUES (102, 'Mom', '78');